### ISSUE TITLE
Compile error Ubuntu 14.04

### ISSUE THREAD

**Issue by jbnl** [Ferro-Crypto/Ferro-project#1]
Hi, when compiling from the latest source, the make command crashes on 36%. How do I get past this error?

> [ 36%] Building CXX object src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/cryptonote_core.cpp.o
> In file included from /usr/local/include/boost/asio/impl/write.hpp:25:0,
>                  from /usr/local/include/boost/asio/write.hpp:927,
>                  from /usr/local/include/boost/asio/buffered_write_stream.hpp:29,
>                  from /usr/local/include/boost/asio/buffered_stream.hpp:22,
>                  from /usr/local/include/boost/asio.hpp:41,
>                  from /ferro/contrib/epee/include/net/abstract_tcp_server2.h:39,
>                  from /ferro/contrib/epee/include/net/levin_server_cp2.h:32,
>                  from /ferro/src/p2p/net_node.h:48,
>                  from /ferro/src/cryptonote_core/cryptonote_core.cpp:47:
> /usr/local/include/boost/asio/detail/consuming_buffers.hpp: In member function ‘boost::asio::detail::consuming_buffers<Buffer, Buffers, Buffer_Iterator>::prepared_buffers_type boost::asio::detail::consuming_buffers<Buffer, Buffers, Buffer_Iterator>::prepare(std::size_t)’:
> /usr/local/include/boost/asio/detail/consuming_buffers.hpp:105:50: error: parse error in template argument list
>      while (next != end && max_size > 0 && result.count < result.max_buffers)
>                                                   ^
> make[3]: *** [src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/cryptonote_core.cpp.o] Error 1
> make[3]: Leaving directory `/ferro/build/release'
> make[2]: *** [src/cryptonote_core/CMakeFiles/obj_cryptonote_core.dir/all] Error 2
> make[2]: Leaving directory `/ferro/build/release'
> make[1]: *** [all] Error 2
> make[1]: Leaving directory `/ferro/build/release'
> make: *** [release-all] Error 2

**Comment by Ferro-Crypto** [comment]
What versions of gcc and boost do you use?

I get a successful build with gcc 5.4 and boost 1.64 on Ubuntu 14.04.

**Comment by jbnl** [comment]
Thanks for your reply. As it turned out I only installed the latest Boost version in /usr/include/boost but not in /usr/local/include/boost - and the way it is compiled it looks for the version in the /local/ folder. Fixed it :)
